/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("createProduct", () => {
    const body: api.Product = undefined
    return expect(instance.createProduct(body, {})).resolves.toBe(null)
  })
  test("deleteProduct", () => {
    const id: string = "id_example"
    return expect(instance.deleteProduct(id, {})).resolves.toBe(null)
  })
  test("getProducts", () => {
    return expect(instance.getProducts({})).resolves.toBe(null)
  })
  test("updateProduct", () => {
    const id: string = "id_example"
    const body: api.Product = undefined
    return expect(instance.updateProduct(id, body, {})).resolves.toBe(null)
  })
})

